export const hardcodedTutoringTestimonials = [
  {
    id: "hc-0",
    name: "Pragna",
    designation: "Physics: 95% | Math: B's to A's",
    school: "",
    rating: 5,
    subject: "Physics & Math",
    content:
      "ACHARYA Educational Services has significantly improved my academic performance in both physics and math. With their guidance, I achieved a 95 on my physics midterm and raised my math test scores from low B's to consistent A's. The tutors are knowledgeable, clear in their explanations, and genuinely committed to student success.",
    successStory: "",
    src: "/testimonial-logos/default.png",
    programs: ["Tutoring"],
  },
  {
    id: "hc-1",
    name: "Adwitha",
    designation: "Math Grade: D to A",
    school: "",
    rating: 5,
    subject: "Math",
    content:
      "Shanti Swaroop is a great tutor and has helped improve in math a lot. I went from a D to an A this year. Math is now easier than before when I was struggling everything finally clicked. My confidence in math has grown throughout the year.",
    successStory: "",
    src: "/testimonial-logos/default.png",
    programs: ["Tutoring"],
  },
  {
    id: "hc-2",
    name: "Lalit Pinisetti",
    designation: "Personalized Learning Success",
    school: "",
    rating: 5,
    content:
      "The tutor is strict with students when he needs to be strict, and gentle with students when he needs to be gentle. He truly understands what each student is capable of and motivates each student precisely enough for their highest chances of success. He makes each topic easy to understand for students and is overall a great teacher.",
    successStory: "",
    src: "/testimonial-logos/default.png",
    programs: ["Tutoring"],
  },
  {
    id: "hc-3",
    name: "Ruhee",
    designation: "AP Calculus Confidence",
    school: "",
    rating: 5,
    subject: "AP Calculus",
    content:
      "I joined because I wanted help in preparing for the AP Calculus exam, and these sessions definitely boosted my confidence in and familiarity with the subject. Shanti provided lots of good practice problems, explained concepts that I didn't understand at first, and was patient if it took me a while to figure something out. Overall, great experience!",
    successStory: "",
    src: "/testimonial-logos/default.png",
    programs: ["Tutoring"],
  },
  {
    id: "hc-4",
    name: "Rishitha",
    designation: "Tailored Learning Method",
    school: "",
    rating: 5,
    content:
      "I have joined these classes to help me get hold and excel in some of the classes that I am taking in school. Shanti Swaroop gained insights on how I learn and tailors the classes based on that which helps me to understand the different concepts even better. His way of teaching is very unique and different from any other tutor.",
    successStory: "",
    src: "/testimonial-logos/default.png",
    programs: ["Tutoring"],
  },
  {
    id: "hc-5",
    name: "Sloane Stenson",
    designation: "Online Learning Success",
    school: "",
    rating: 5,
    content:
      "Shanti Swaroop is very helpful to me as my tutor. He thoroughly explains every question I have to me and provides me with extra practice when needed. Being available via zoom makes tutoring easier and more accessible.",
    successStory: "",
    src: "/testimonial-logos/default.png",
    programs: ["Tutoring"],
  },
  {
    id: "hc-6",
    name: "Geetika",
    designation: "Pre-Calculus Mastery",
    school: "",
    rating: 5,
    subject: "Pre-Calculus",
    content:
      "I joined these classes because I need help with Pre-Calculus, and every time I come to my classes I leave feeling more confident in the topic I am learning. Going to these classes helped me improve my test scores and helped me improve my overall grade in my pre-calculus class.",
    successStory: "",
    src: "/testimonial-logos/default.png",
    programs: ["Tutoring"],
  },
  {
    id: "hc-7",
    name: "IM1 Tutoring: Sutter Middle School",
    designation: "Patient Teaching Approach",
    school: "",
    rating: 5,
    subject: "IM1",
    content:
      "Shanti Swaroop is very patient and positive. Our daughter is having difficulty keeping up with the pace of her teacher at school. Shanti is better at explaining the concepts and allows her time to learn. He is very encouraging and helps to boost her confidence.",
    successStory: "",
    src: "/testimonial-logos/default.png",
    programs: ["Tutoring"],
  },
  {
    id: "hc-8",
    name: "Pre-Calc Tutoring: Folsom High School",
    designation: "Interactive Learning",
    school: "",
    rating: 5,
    subject: "Pre-Calculus",
    content:
      "Amazing Service! Shanti Swaroop is very interactive and focused with my kid. He explains concepts very well in multiple different ways and also a very nice and understanding person. Great Tutor!",
    successStory: "",
    src: "/testimonial-logos/default.png",
    programs: ["Tutoring"],
  },
  {
    id: "hc-9",
    name: "IM3 Tutoring: Folsom High School",
    designation: "Flexible Scheduling",
    school: "",
    rating: 5,
    subject: "IM3",
    content:
      "Shanti Swaroop has flexible scheduling and we worked together to find the best days to meet that provide the most benefit for my son. He makes sure that my son is not just working on math when he is in his session but rather, he also asks that my son check in, provides updates and samples of what he is working on.",
    successStory: "",
    src: "/testimonial-logos/default.png",
    programs: ["Tutoring"],
  },
  {
    id: "hc-10",
    name: "IM2 Tutoring: Folsom High School",
    designation: "Professional Methodology",
    school: "",
    rating: 5,
    subject: "IM2",
    content:
      "Shanti Swaroop is a great Tutor! He is very professional and organized in his methodology. You can tell right away that he cares about the students. He provides a game plan for his students. Would definitely recommend him.",
    successStory: "",
    src: "/testimonial-logos/default.png",
    programs: ["Tutoring"],
  },
  {
    id: "hc-11",
    name: "IM1 Tutoring: Folsom High School",
    designation: "Concept Breakdown",
    school: "",
    rating: 5,
    subject: "IM1",
    content:
      "Shanti has been really good about breaking down the steps of my son's struggles. He provided help with preparing for quizzes and tests. He has provided tips and tricks that helped math concepts makes sense that common core just is not accomplishing.",
    successStory: "",
    src: "/testimonial-logos/default.png",
    programs: ["Tutoring"],
  },
];
